--- 
title: "ASReview CLI"
software:
- '[ASReview](https://asreview.nl/)'
login:
- cli
os_flavor: linux
os:
- Ubuntu 22.04
data:
- ResearchDrive
packages: []
gpu: true
admin: true
support: UU
---

## Description
This workspace can be used to work with ASReview (e.g. for simulations) via the command line interface (CLI).

Currently the workspace is only available [upon request](../../contact.qmd).

## Creation

### Create a storage volume
First create a storage volume before creating the workspace.

See the [Getting started](../../first-steps.qmd#create-storage-volume) page for more info about how and why to create a storage volume.

### Create a workspace

In the [Research cloud portal](https://portal.live.surfresearchcloud.nl) click the 'Create a new workspace' button and follow the steps in the wizzard.

See the [Getting started](../../first-steps.qmd#create-a-workspace) page for more guidance.

**Choosing the number of CPU cores**: A workspace with more CPU cores and RAM memory will cost more credits. If you want to use a large workspace for a long period of time (many days or weeks), first try to test on small machines (e.g. a 2 core and a 4 core machine) whether a bigger machine actually does help you to get your results faster.

## Access options
This workspace can be accessed using SSH (secure shell protocol). The research cloud documentation provides instructions on [how to set up SSH for research cloud](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-AccessaworkspacewithSSH).

To connect to the workspace from a Windows computer you need specific software to use a 'shell' (also known as 'terminal'), examples include Git Bash, PuTTY and MobaXterm. If you need to install something new, we would recommend [MobaXterm](https://mobaxterm.mobatek.net/)

On MacOS and Linux machines you can use the standard 'Terminal'.

## Data transfer options

When the workspace is up and running the first thing you probably need to do is transfer your dataset to the storage volume that is attached to your workspace. The storage volume can be found on the following directory path: `~/data/volume_2/`. Create a folder there where you want to store your data. There are several methods to transfer data to the workspace, the recommended method depends on where the data is currently stored:

### Data is stored on your PC
When the dataset is stored on the computer you are working on now, you can use the `scp` command to tranfer files or folders, or the `rsync` command to 'synchronize' folders. If you have `rsync` installed, we would recommend this over `scp`, but `scp` is also fine.

[Instructions](../../manuals/ssh-data-transfer-methods.qmd)

### Data is stored on Surfdrive (or Researchdrive, Onedrive, Dropbox, etc.)
When data is stored on Surfdrive (or Researchdrive, Onedrive, Dropbox, etc.), data transfer can be done using Rclone.

[Instructions](../../manuals/rclone-researchcloud.qmd)

### Data is stored on Yoda

When your data is stored on Yoda, data transfer can be done using iRODS icommands.

[Instructions](../../manuals/icommands.qmd)


## Usage

ASReview and all of its extensions are preinstalled in a 'conda' environment. To be able to use asreview, the user should run the following commands:

`/etc/miniconda/bin/conda init`

Now `logout` and re-login to apply the changes.

`conda activate asreview`

Now to test if ASReview is installed:

`asreview -h`

## Tips

To practice with navigation, finding files and folders, and running programs via a Linux command line interface check this [Software Carpentries course](https://swcarpentry.github.io/shell-novice/)
