--- 
title: "ASReview"
software:
- '[ASReview](https://asreview.nl/)'
login:
- webapp-sso
os_flavor: linux
os:
- Ubuntu 22.04
packages: []
gpu: true
admin: false
support: UU
---

## Description

ASReview LAB is an open-source machine learning tool designed to streamline the systematic screening and labeling of large textual datasets. It is widely used for tasks such as title and abstract screening in systematic reviews or meta-analyses, but its applications extend to any scenario requiring systematic text screening.

This workspace type will start ASReview as a webapplication.

Anyone who has access to your [Collaboration](../../glossary.qmd#collaboration) will be able to easily login to ASReview [using Single-Sign on](../../first-steps.qmd#webapplications-that-support-single-sign-on.). Since ASReview 2.0 supports multiple users, this workspace is ideal for crowd-based screening. Simply add the members of your screening group to your [Collaboration in SRAM](../../glossary.qmd#collaboration)!

Extensions (such as `asreview-dory`) are not installed on this workspace. 

Please also read the [tips](#tips) below.

## Creation

{{< include ../partials/_storage.qmd >}}

**If you select a storage unit when creating an ASReview workspace, all ASReview data will automatically be stored on it.** Since ASReview can potentially generate a lot of data, using a storage unit may be advised (the default, non-permanent storage on the workspace amounts to 150GB). 

{{< include ../partials/_creation.qmd >}}

**Choosing the right hardware**: ASReview uses an AI model that runs in parallel to the ASReview webapplication. **It is therefore recommended to choose a workspace with at least two CPU cores. Four CPUs is probably enough for most cases.** The more users that will be using the workspace to do screening in parallel, the more hardware will be required.

Please also see the [tips for responsible use](../../responsible-use.qmd).

## Access

This workspace can be accessed via the yellow 'Access' button, or by opening the URL listed in the dashboard in your browser. Any member of the collaboration can login to the workspace [using Single-Sign On](../../first-steps.qmd#webapplications-that-support-single-sign-on.).

### Command line

Alternatively, *only those users who are admins in the Collaborative Organisation* (in the `src_co_admin` group) can [login to the workspace via the commandline](../../first-steps.qmd#ssh), using `ssh`. This may be useful for running ASReview in [simulation mode](https://asreview.nl/simulate/), or e.g. for making backups.

After logging in, the `asreview` command will be on your path. The `ASREVIEW_PATH` environment variable will be set to reflect the location of ASReview's data (default: `/var/www/asreview/asreview_data` if you do __not__ create the workspace with a storage unit, `/data/yourstoragename/asreview_data` if you __did__), so you should be able to interact with it straight away.

Admin users will also be able to use `sudo` (after entering their time-based passwords).

## Usage

When you log in to this workspace, the ASReview  web app will open automatically. 

## Tips

- Remember that you are responsible for making backups of any data yourself! This also applies when using a storage unit. Although data on a storage unit will not be deleted when you delete the workspace, it can still become corrupt. So if it is important to your work, make sure to make periodical (e.g. daily or weekly) backups of your projects. You can make a backup by [logging in to the workspace using the commandline](#command-line), or by downloading your project from the webapplication.
- Remember that ASReview may potentially generate a lot of data, so think about how much storage you may need. For most cases, the standard amount of storage should be enough. But if you're unsure, [just ask for advise](../../contact.qmd)!
- Similarly, think about how many resources (CPUs) your workspace will need. Again, if you're unsure, [just ask for advise](../../contact.qmd)!
