--- 
title: "Matlab"
software:
- Matlab
login:
- desktop
- cli
os_flavor: linux
os:
- Ubuntu 22.04
data:
- ResearchDrive
- irods-icommands
- Yoda Webdav
misc:
- License needed
packages: []
gpu: false
admin: true
support: UU
---

## Description

This workspace is an Ubuntu Desktop workspace with MATLAB installed. Ubuntu Desktop is a linux operating system but has a Graphical User interface so operating it is similar to using a Windows operating system. 

{{< include ../partials/_creation.qmd >}}

## Access
This workspace can be accessed via the yellow 'Access' button. You need a TOTP to login to your workspace, see [Workspace access with TOTP](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-WorkspaceAccesswithTOTP).

{{< include ../partials/_data_transfer.qmd >}}

The recommended [iBridges client for Yoda and iRODS](../../manuals/ibridges.qmd) is preinstalled.

## Usage
### Prerequisites:
You will need a Mathworks account and add you UU licence to this account to be able to use MATLAB. Find instructions on how to do this [here](https://intranet.uu.nl/en/knowledgebase/matlab)

### Activate MATLAB
When logged in to the workspace:

1. Click 'Applications' in the top left corner 
2. Click 'Development'
3. Click 'Matlab Activate', a wizard will open.
4. Click 'Next' to activate Matlab using the internet
5. Login to your Mathworks account. For the password, it will ask you to get a 6 digit password from: [https://nl.mathworks.com/mwa/otp](https://nl.mathworks.com/mwa/otp)
6. Continue the wizard and choose the default options until you are finished.

### Open MATLAB

1. Click 'Applications' in the top left corner
2. Click 'Development'
3. Click 'Matlab'

## Tips
