--- 
title: Miniconda (shared)
software:
- miniconda
login:
- desktop
- cli
os_flavor: linux
os:
- Ubuntu 22.04
data:
- ResearchDrive
- irods-icommands
- Yoda Webdav
- iBridges (python)
packages:
- Custom Packages
gpu: false
admin: true
support: UU
---

## Description

This workspace types comes with the `miniconda` package manger preinstalled. All users on the system will share the same `conda` environment. **Warning:** although this can be convenient for some usecases, this can lead to unwanted conflicts/interference. In most cases, it is recommended to use separate `conda` environments for each user. You can use the [Python Workbench](./python-workbench.qmd) Catalog Item for this.

There are various flavours of this Catalog Item:

- Miniconda CLI (shared) ([login via command line](../../first-steps.qmd#ssh))
- Miniconda Desktop (shared)([login via desktop](../../first-steps.qmd#browser-access-to-a-desktop-environment))

Simply choose the one that is most convenient to you.

If needed, we can help you to automatically install certain packages when the workspace is created. Please [contact us](../../contact.qmd) for this. 

## Creation

{{< include ../partials/_storage.qmd >}}

{{< include ../partials/_creation.qmd >}}


## Usage

When you login, `miniconda` will be ready for use. See the [miniconda docs](https://docs.anaconda.com/free/miniconda/).

`miniconda` will be installed to `/opt/miniconda`.

{{< include ../partials/_data_transfer.qmd >}}

The recommended [iBridges client for Yoda and iRODS](../../manuals/ibridges.qmd) is preinstalled.

### Installing additional software

The user has [admin rights](../../responsible-use.qmd#installation-of-software) to install additional software on the system (on a terminal, use `sudo <yourcommand>`).

## Tips

{{< include ../partials/_security.qmd >}}