--- 
title: Python Workbench
software:
- Python
- poetry
- miniconda
- uv
login:
- desktop
- cli
os_flavor: linux
os:
- Ubuntu 20.04
- Ubuntu 22.04
data:
- ResearchDrive
- irods-icommands
- Yoda Webdav
- iBridges (python)
packages:
- Custom Packages
gpu: false
admin: true
support: UU
---

## Description

This workspace types comes with various Python development tools already installed:

- `uv` for installing different python versions and dependencies lightning fast
- `pyenv` for managing different python versions
- `miniconda` for managing dependency environments
- `poetry` for an alternative way of running projects with specified dependencies

There are various flavours of this Catalog Item:

- Python Workbench CLI ([login via command line](../../first-steps.qmd#ssh))
- Python Workbench Desktop ([login via desktop](../../first-steps.qmd#browser-access-to-a-desktop-environment))

Simply choose the one that is most convenient to you.

### Tools are installed in userspace

Note that the above tools are installed *separately* for each user in your [CO](../../glossary.qmd#collaboration) that has access to the machine. This means each user can have their own clean python environments.

If you prefer all users on the machine to have a single shared `miniconda` environment, please see the [Miniconda Catalog Item](./miniconda.qmd).

## Creation

{{< include ../partials/_storage.qmd >}}

{{< include ../partials/_creation.qmd >}}

## Access

### Python Workbench CLI

For the Python Workbench CLI (command line) flavour of this Catalog Item, you can [login using SSH](../../first-steps.qmd#ssh).

### Python Workbench Desktop

For the Python Workbench Desktop flavour of this Catalog Item, you can [login using your browser](../../first-steps.qmd#browser-access-to-a-desktop-environment). It is also possible to login via SSH, as described above.

## Usage

The first time (but only the first time) you login to a workspace of this type, the Python tools (`pyenv`, `miniconda` and `poetry`) are installed for your user. This means that at first login you may experience a small delay (~1 minute maximum). During this time, if you are logging in on the command line, you will see that the applications are being installed for you:

```
--- Running install scripts at first login: executing /home/username/runonce.d/01_pyenv-install.sh
--- Running install scripts at first login: executing /home/username/runonce.d/10-poetry.sh
--- Running install scripts at first login: executing /home/username/runonce.d/runonce_conda.sh
```

When you are logged in you can start developing or running code. On the command line, you will have `uv`, `pyenv`, `miniconda`, and `poetry` available.

### Python environments
You can use `uv`(recommended) or `pyenv` to install and select a different (newer) Python version, and create virtual environments.

#### `uv`
In your project folder, create a virtual environment with a specific Python version (e.g. 3.12):
`uv venv --python 3.12`
See the [uv docs](https://docs.astral.sh/uv/concepts/python-versions/) or [tutorials](https://docs.astral.sh/uv/guides/) to learn more.

#### `pyenv`
In your project folder, create a virtual environment with a specific Python version (e.g. 3.12):
`pyenv virtualenv 3.12 myprojectenv`

See the [pyenv docs](https://github.com/pyenv/pyenv#usage).

#### Others
To start using `miniconda` environments, activate `conda` with the command `conda init`. See the [miniconda docs](https://docs.anaconda.com/free/miniconda/).

Also see the [poetry docs](https://python-poetry.org/docs/).

{{< include ../partials/_data_transfer.qmd >}}

The recommended [iBridges client for Yoda and iRODS](../../manuals/ibridges.qmd) is preinstalled.

#### VSCodium code editor (Desktop only)

Under 'Applications' (topleft corner) you can find the code editor ['VSCodium'](https://vscodium.com/) (an open source alternative to VS Code) under 'Development'. VSCodium can be used for writing python scripts, Jupyter notebooks, etc.

#### Jupyter lab interface (Desktop only)

If you prefer a juypter notebook interface over VSCodium for editing notebooks, open a terminal and use the following commands to install Jupyter:

```
cd <your project folder>
uv venv --python 3.12
source .venv/bin/activate
uv pip install jupyter
```

### Installing additional software

The user has [admin rights](../../responsible-use.qmd#installation-of-software) to install additional software on the system from the terminal.

## Tips

{{< include ../partials/_security.qmd >}}
