--- 
title: "RStudioUU"
software:
- RStudio
login:
- webapp-sso
os_flavor: linux
os:
- Ubuntu 24.04
packages: []
gpu: true
admin: true
support: UU
---

## Description

[RStudio](https://posit.co/products/open-source/rstudio) is a powerful integrated development environment (IDE) for R, providing a user-friendly interface for writing and executing R code, managing projects, and creating visualizations.

Each logged-in user on this workspace gets their own instance of RStudio with access to R packages and project management tools.

Login is done via [SRAM](https://servicedesk.surf.nl/wiki/spaces/IAM/pages/74226073/SURF+Research+Access+Management).

## Creation

{{< include ../partials/_storage.qmd >}}

{{< include ../partials/_creation.qmd >}}

## Access
This catalog item uses SURF Research Access Management [(SRAM)](https://servicedesk.surf.nl/wiki/spaces/WIKI/pages/195854422/Workspace+access+with+SRAM) authentication. In your SURF Research Cloud Dashboard,simply click on the yellow Access button and login via your instituional credentials (solis-id for UU users).

In order to be able to request access to Catalog Items, you must be marked as having the **'Developer'** role in your [Collaboration](https://utrechtuniversity.github.io/vre-docs/docs/glossary.html#collaboration) in SRAM. *This is the case by default if the CO was created for you.* However, if you were invited later, it may be necessary to add yourself (or ask your CO-admin to add you) to the `src_co_developer` group.

Follow the steps mentioned here to [request access](../../manuals/catalog-item-access.qmd).

{{< include ../partials/_data_transfer.qmd >}}

## Usage

After logging in, RStudio will be accessible through your web browser. 

**Getting Started with R**

- Create a new file or project via the menu in the top left
- Install R packages: Use `install.packages("package-name")` in the console
- Write R scripts and save them in your project directory
- Run code directly in the console or

For reproducible R environments with package management, see the [manual for best practices with R environments](../../manuals/r-environment.qmd).

For detailed guides on using RStudio's features, see the [RStudio documentation](https://docs.posit.co/ide/user/).

## Tips
{{< include ../partials/_sudo-rights.qmd >}}

{{< include ../partials/_security.qmd >}}