title: VRE Docs
email: info.rdm@uu.nl
description: >- # this means to ignore newlines until "baseurl:"
  This site contains user documentation for VREs for UU researchers.
baseurl: /vre-docs # the subpath of your site, e.g. /blog

theme: jekyll-theme-slate
markdown: kramdown
include: ['_pages']
