project:
  type: website
  output-dir: ./_html

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/research-cloud-intro.qmd
        text: Introduction
      - href: docs/onboarding.qmd
        text: Get started
      - href: docs/first-steps.qmd
        text: First steps
      - href: docs/workspace-catalogue.qmd
        text: Workspaces
      - href: docs/manuals.qmd
        text: Manuals
      - href: docs/terms-of-use.qmd
        text: Terms of use
      - href: docs/contact.qmd
        text: Contact
  repo-url: https://github.com/UtrechtUniversity/vre-docs
  repo-actions: [edit]

format:
  html:
    theme: cosmo
    css: _styles/styles.css
    toc: true
    code-copy: true
    monobackgroundcolor: "#f8f9fa"
    code-block-background: true
