--- 
title: "ASReview Lab"
---

## Description
This workspace can be used to work with ASReview Lab.

Currently the workspace is for all Research Cloud users.

## Creation

### Create a storage volume
First create a storage volume before creating the workspace.

See the [Getting started](getting-started.qmd#create-storage-volume) page for more info about how and why to create a storage volume.

### Create a workspace

In the [Research cloud portal](https://portal.live.surfresearchcloud.nl) click the 'Create a new workspace' button and follow the steps in the wizzard.

See the [Getting started](getting-started.qmd#create-a-workspace) page for more guidance.

**Choosing the number of CPU cores**: A workspace with more CPU cores and RAM memory will cost more credits. If you want to use a large workspace for a long period of time (many days or weeks), first try to test on small machines (e.g. a 2 core and a 4 core machine) whether a bigger machine actually does help you to get your results faster.

## Access
This workspace can be accessed via the yellow 'Access' button. You need a TOTP to login to your workspace, see [Workspace access with TOTP](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-WorkspaceAccesswithTOTP).

## Data transfer options
### Internet Browser 
The most intuitive way to get your dataset to the workspace is by using a cloud storage platform (e.g. Surfdrive, Yoda, etc.). Within the workspace you can click 'applications' (topleft corner) and then open an internet browser. Use the internet browser and go to the web portal of the storage platform you use to download the data to the workspace.

### Command line
Alternatively it is possible to transfer data using command `scp`. For this you need to work with a command line application (or aka terminal) on your PC and you need get the IP address of the Workspace from the Research Cloud portal. Find complete instructions [here](../manuals/ssh-data-transfer-methods.qmd)

## Usage
When you log in to this workspace, the ASReview lab web app will open automatically. 

## Tips
Before you log out and/or delete a workspace, don't forget to store the results either on the storage unit (located under `/data/volume_2`), or upload it to an online storage platform using an internet browser _within_ the workspace.
