---
title: "Installing and using iCommands on Surf Research Cloud"
---

The instructions below describe the process of data transfer between Surf Research Cloud and [Yoda](https://www.uu.nl/en/research/yoda) using iCommands. This manual is developed for workspaces based on a Linux operating system (such as Ubuntu and Python Workspaces as well as Jupyter Notebook and RStudio workspaces). Transfer is also possible via the Webdav protocol using [Rclone](https://rclone.org). However, for large files iCommands is faster due to parallel transfer options.

### Prerequisites
You will need some basic linux skills to be able to use the iCommands successfully. 
If you don't have these skills, take some time to practice using sections 1, 2, 3 and 7 of this short [online course](https://swcarpentry.github.io/shell-novice) before proceeding. You can practice in the terminal (see step 1).

You will also need access to [Yoda](https://www.uu.nl/en/research/yoda).

### Step 1: Make sure you are in a terminal
- In a Jupyter based workspace such as [VRE Lab](../workspaces/programming/vre-lab.qmd) in Research cloud: 
  To open a new terminal, click the + button in the file browser and select the terminal in the new Launcher tab
  ([find a short video here](https://jupyterlab.readthedocs.io/en/stable/user/terminal.html)).
- In Rstudio ([Rstudio workspace](../workspaces/programming/rstudioUU.qmd) in Research cloud):
  In the bottom left panel, click the 'terminal' tab.
- In [Python](../workspaces/programming/python-workbench.qmd) and [Ubuntu](../workspaces/plain/ubuntu.qmd) Desktop workspaces:
  Open a terminal. You can find it under Applications.
- In [Python](../workspaces/programming/python-workbench.qmd) and [Ubuntu](../workspaces/plain/ubuntu.qmd) CLI workspaces:
  You are already in a terminal after logging in to the workspace. 


### Step 2: Install iRODS iCommands
Some workspaces have iRODS iCommands preconfigured. This should be visible in step 1 when creating a workspace.

Copy and paste (or type) the following commands in the terminal, or view the most up to date installation instructions for iRODS iCommands on the [yoda website](https://www.uu.nl/en/research/yoda/guide-to-yoda/i-am-using-yoda/using-icommands-for-large-datasets) in the section "Installing iCommands on Ubuntu". 

```
sudo apt-get update
sudo apt-get install -y lsb-release
wget -qO - https://packages.irods.org/irods-signing-key.asc | sudo apt-key add - 
sudo echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods.list
sudo apt-get update
sudo apt-get install -y irods-icommands
```

### Step 3: Create a config file

{{< include partials/_irods_env.qmd >}}

### Step 4: Initialize connection to iRODS

Navigate out of the `.irods` folder and to a folder where you want to move files from Yoda. Run `cd ~` to navigate to your home directory and then run the following command to initialize the connection to iRODS:

```
iinit
```

If you see `command not found: iinit` after running the command, it means that iCommands is not properly installed. Run `sudo apt-get install -y irods-icommands` to install iCommands and try again.

After running `iinit`, you will be prompted to enter your Yoda password. You can find this as a [data access password](https://www.uu.nl/en/research/yoda/using-data-access-passwords). This is not the same as your Research Cloud or solis-id password.

Type `ils` to see whether the connection has been established. The output of the `ils` command will list the current Yoda folder and the folders that are located within the current folder.

`iinit` and `ils` are commands which can only be used when icommands is active. Some of these commands are very similar to standard unix commands. When icommands is active you can still operate the HPC system using normal unix commands. A complete list of all 'icommands' can be found [here](https://docs.irods.org/4.2.9/icommands/user/).

### Step 5: Transferring data

Standard transfer of a single file can be done using `iget` (to retrieve from Yoda to your workspace) and `iput` (to upload to Yoda from your workspace).
```
iget /uu/home/<Yoda-folder-name>/<file-name>
iput <workspace-file-name> /uu/home/<Yoda-folder-name>/
```

The `irsync` command can be used to synchronize entire directories between Yoda and Cartesius. The command is used as follows.

```
irsync <source> <destination>
```

In contrary to the `iput` and `iget` commands, in `irsync` it is necessary to put 'i:' before the Yoda path. The Yoda path (directly after 'i:') to the folder that should be synchronized should be relative to the **current** Yoda folder (check with `ils`).

E.g.

```
irsync -rKV i:myfolder /my_researchcloud_folder
```

`-rKV` means the following flags (options) are used:

* `-r` recursive - store the whole folder including subdirectories
* `-K` Calculate and verify the checksum on the data
* `-V` Very verbose

Typically you will want to store data on the (persistent) storage volume that is attached to your workspace. Transfer it directly there as follows:

```
irsync -rKV i:myfolder ~/data/volume_2/my_destination_folder
```


To synchronize in the opposite direction

```
irsync -rKV /my_researchcloud_folder/ i:myfolder
```

> note the '/' at the end of /my\_researchcloud\_folder/ that is not used in the command above.

### Parallel transfer

With icommands it is possible to transfer individual files in parallel using multiple threads, which results in higher transfer speeds. The flag `-N` can be used to control the number of parallel threads (only recommended in very specific situations). When not specified the server decides a default number of threads. For large files this number can be e.g. 16 threads.

```
irsync -rKV -N 0 i:myfolder /my_researchcloud_folder
```
