---
Title: "Install Rclone"
---

The steps below are used to install Rclone on Research Cloud.

### Step 1: Make sure you are in a terminal
- In Jupyterhub ([Jupyter Workspace](../workspaces/programming/jupyter.qmd) or [VRE Lab](../workspaces/programming/vre-lab.qmd) in Research cloud)
  - To open a new terminal, click the + button in the file browser and select the terminal in the new Launcher tab
  ([find a short video here](https://jupyterlab.readthedocs.io/en/stable/user/terminal.html)).

- In Rstudio ([Rstudio workspace](../workspaces/programming/rstudio.qmd) in Research cloud)
  - In the bottom left panel, click the 'terminal' tab.

- In [Python Desktop workspaces](../workspaces/programming/python-workbench.qmd) and [Ubuntu workspaces](../workspaces/plain/ubuntu.qmd), simply open the 'Terminal' application (found under Applications.)

- [Python CLI workspaces](../workspaces/programming/python-workbench.qmd) will open a terminal by default.

- To run rclone in [Windows workspaces](../workspaces/plain/windows.qmd), the installation steps are slightly different. Check out the [Windows installation manual](../manuals/rclone-windows.qmd) for more information.

### Step 2: Download and install rclone

Type the following command in the terminal:

`curl https://rclone.org/install.sh | sudo bash`

### Step 3: Check if installation was successful

Type the following command. A version number will be displayed when installation was successful.

``` bash
rclone version
```


### Next: [Configure Rclone](rclone-config.qmd)
