---
title: "Configuring Rclone for Surfdrive and Researchdrive"
---

Rclone has an interactive menu to generate a config file for you. You need to complete this menu once for each storage platform that you want to connect to. You can use Rclone for many different types of storage platforms: check the [homepage](https://rclone.org) for a list. [SURFdrive](https://www.surf.nl/en/services/storage-data-management/surfdrive) and [Research drive](https://uu.data.surf.nl) are based on Nextcloud software. Platforms built on standard protocols such as WebDAV (including Yoda, Data Archive or the U: network drive of UU student and employees) are also supported but require slightly different configuration steps.
To transfer data from Yoda, [iBridges](../manuals/ibridges.qmd) or [iCommands](../manuals/icommands.qmd) are recommended.

To check whether Rclone is available on your system:

``` bash
rclone version
```

You should see a version number displayed in the terminal.

The steps below describe how to set up rclone for Surfdrive. The steps for setting up rclone for Researchdrive are similar.

To start the interactive menu:

``` bash
rclone config
```

You will see a list of options and current remotes (if any). For SURFdrive you need the following information (for Rclone version 1.73.1):

1. Type `n` for New remote

2. You can choose a name for your remote e.g. `surfdrive` (or SD)

3. After choosing your remote name, you will be prompted to choose a storage type. Select the option for **WebDAV** (`62` for Rclone version 1.73.1. However, depending on your Rclone version this number may be different!)

4. You will be asked to fill in the URL. You can look this up via the web portal of [SURFdrive](https://surfdrive.surf.nl/).
   - In the top right corner click on your account name. Go to settings. 
   - In the left panel, click security. Here, you can find your the url to access your files via WebDAv. It should be something like https://surfdrive.surf.nl/files/remote.php/nonshib-webdav.

5. Before you continue with the Rclone config menu in your workspace terminal, first perform the following step via the [web portal](https://surfdrive.surf.nl) of SURFdrive.
   - Fill in an **app name** (e.g. lisa) on the security settings page (same page as previous step) and click `create new app password`. 
   - This will show a username and a password. You will need these in the following steps of the Rclone menu. **Make sure to copy the password and save it somewhere, you will not be able to access it again after closing the pop-up!** 

6. Back in your terminal, enter the url from step 4.

7. Select the type of WebDAV storage system. Type: `2` for Nextcloud.

8. Type in your user name from SURFdrive (this is the username found in the web portal (step 5))

9. You will be prompted for a password. Enter `y` to select y) Yes type in my own password

10. Type in your password from the web portal and type it in again for confirmation (**Note that you will not see the password when you type it in, this is normal!**)

11. Skip the Bearer token option by pressing `Enter`.

12. Choose `n` to skip the advanced config

13. You will see a Configuration Complete text. Confirm your settings by typing `y`. You will see a message that the new remote has been added.

14. Finally, choose `q` to quit the menu.

Test whether everything is setup correctly by typing the following command in the terminal, if necessary change `surfdrive:` to any other name chosen in step 2.

``` bash
rclone lsd surfdrive:
```

If everything is setup correctly, you should see a list of files and folders that are present on your SURFdrive.

### Next: [Using rclone for data transfer](rclone-transferringdata.qmd)

