---
title: "First steps"
---

This page describes all general steps that a user needs to perform to be able to start working with SURF Research cloud:

Contents:

1. [Creating storage](#create-storage)
2. [Creating a workspace](#create-a-workspace)
3. [Pausing, Resuming, Deleting a workspace](#pausing-resuming-deleting-a-workspace)
4. [Logging in to your workspace](#getting-access-to-your-workspace)
5. [Getting data inside your workspace](#getting-data-inside-your-workspace)

## Research Cloud portal

When you have completed an [onboarding procedure](onboarding.qmd), you can login using the following link: 

[**Research Cloud portal**](https://portal.live.surfresearchcloud.nl/)

## Create storage volume

### Why a storage volume?
In most cases you need to create a storage volume before you create a workspace. A workspace has limited storage and is temporary; all data stored on the workspace itself are deleted when a workspace is deleted. You can see a storage volume as a USB stick that you can attach to a workspace. A storage volume is persistent, so when you remove a workspace, all data on the storage volume will remain there. Storage volumes have good performance and are suitable for I/O-intensive computing tasks.

### How to create a storage volume?
In the Research Cloud portal:

-   Click 'Create new storage'
-   The Wizard will guide you through the steps, some tips:
-   Choose Storage HPC
-   Choose the [Collaborative Organization](https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=17825822) of the project for which you want to create the storage volume
-   Choose the wallet with which you 'pay' for the Storage Unit
-   Choose the size. It is not possible to resize it later on, so don't choose too small, but also don't choose too large because it will cost more credits.
-   Give your storage volume a descriptive name so you can recognize it later on (recommended: use one or two words separated with and underscore)

### Where can I find the storage volume?
When you created a workspace and chose to attach a storage volume to the workspace (see below), the storage volume can be found under the directory path: `/data`
Typically you want to create a project folder on the storage volume (e.g. `/data/my_storage/my_project`).

## Create a workspace
A workspace can also be called a 'Virtual Machine' or a 'Server'. It is a temporary 'remote' machine that you can login to and that has you can use to perform analyses or model runs. You 'pay' for the machine with the credits from your wallet. The more compute power you select the more credits it costs and the sooner your wallet will be empty.

See [here](manuals/creating.qmd) for detailed information on how to create a workspace.

## Pausing, Resuming, Deleting a workspace
You always need a wallet to create a workspace, by default a workspace can only be paused, resumed and deleted by the one that has created it. You can use SRAM to give persons permission to PAUSE, RESUME and DELETE a workspace that is created by someone else. It is also possible to share a wallet with a member of your CO in SRAM. See [Add collaborators to existing project](https://servicedesk.surf.nl/wiki/display/WIKI/Invite+admins+and+members+to+a+collaboration).


## Getting access to your workspace

There are several ways to login to your workspace. 

### Browser access

#### When?
This is the easiest method and it can be used for most workspaces that have a Graphical user interface (Rstudio, Jupyter Notebook, Ubuntu Desktop, Matlab). It can not be used for Windows server. 
You can check if this method works for your workspace: look up your created workspace under workspaces in the dashboard of the research cloud portal. Click on the workspace (anywhere but don't click the access button) and check the URL in the overview that opens. If the URL has an `https://` address it can be accessed via the browser.

#### How?
To be able to login via the Browser you need to [setup a Time Based Password for your Research Cloud account](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-WorkspaceAccesswithTOTP).

The workspaces can be accessed via your web browser by clicking the yellow access button. The username that you need to type when you want to access the workspace can be found under the 'Profile' tab in the Research Cloud portal. The password to fill in is the Time based password (aka TOTP password) from the authenticator app on your mobile phone.

### RDP (Remote Desktop Protocol)

#### When?
This method can be used for most Windows Server workspaces, and any other workspaces that have an URL starting with `RDP://` when you click on the workspace in the research cloud portal.

#### How?
To be able to login via RDP you need to [setup a Time Based Password for your Research Cloud account](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-WorkspaceAccesswithTOTP).

You need an Remote Desktop client to be able to connect via RDP. On a Windows and MacOS PC you can use an application called 'Remote Desktop', on Linux we recommend 'Remmina'.

The username that you need to type when you want to access the workspace can be found under the 'Profile' tab in the Research Cloud portal. The password to fill in is the Time based password (aka TOTP password) from the authenticator app on your mobile phone.

### SSH

#### When?
For some workspaces this is the only option to login to your workspace. These are typically command line only workspaces (e.g. Ubuntu 20.04 command line).

Since connection via SSH also works for most other workspace types, it could also be a useful option in some other scenarios, e.g. when you want to [copy a file from your laptop to the workspace](manuals/ssh-data-transfer-methods.qmd).

#### How?
The research cloud documentation provides instructions on [how to set up SSH for research cloud](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-AccessaworkspacewithSSH).

To connect to the workspace from a Windows computer you need specific software to use a ‘shell’ (also known as ‘terminal’), examples include Git Bash, PuTTY and MobaXterm. If you need to install something new, we would recommend [MobaXterm](https://mobaxterm.mobatek.net/).

On MacOS and Linux machines you can use the standard ‘Terminal’.

## Getting data inside your workspace

### Mounting online storage
If you have a Research Drive account, you can mount it in your workspace. This method is most easy, and works good for working with small datasets (e.g. <1 GB).

### Transferring data
In many cases it is more reliable to get a copy of your data on the Storage unit that is attached to your workspace.  
Depending on where your data is stored and the workspace that you are using, the following options are available:

-   Upload from your laptop (Jupyter Notebook and Rstudio Workspaces)
-   [scp/ssh](manuals/ssh-data-transfer-methods.qmd) (most workspaces)
-   Download using the internet browser (on Ubuntu Desktop and Windows workspaces, for data stored on e.g. surfdrive, onedrive, etc.)
-   [irods icommands](manuals/icommands.qmd) (for data stored on Yoda, works on Ubuntu based workspaces (including Jupyter and Rstudio)
-   [rclone](manuals/rclone-researchcloud.qmd) (for data stored on a cloud storage platform (e.g. surfdrive, onedrive, dropbox)

