---
title: "Getting Started"
---

[UNDER DEVELOPMENT]
This page describes all general steps that a user needs to perform to be able to start working with SURF Research cloud:

Contents:

1. [Creating storage](#create-storage)
2. [Creating a workspace](#create-a-workspace)
3. [Pausing, Resuming, Deleting a workspace](#pausing-resuming-deleting-a-workspace)
4. [Logging in to your workspace](#getting-access-to-your-workspace)
5. [Getting data inside your workspace](#getting-data-inside-your-workspace)

## Create storage volume

### Why a storage volume?
In most cases you need to create a storage volume before you create a workspace. A workspace has limited storage and is temporary; all data stored on the workspace itself are deleted when a workspace is deleted. You can see a storage volume as a USB stick that you can attach to a workspace. A storage volume is persistent, so when you remove a workspace, all data on the storage volume will remain there. Storage volumes have good performance and are suitable for I/O-intensive computing tasks.

### How to create a storage volume?
In the Research Cloud portal:

-   Click 'Create new storage'
-   The Wizard will guide you through the steps, some tips:
-   Choose Storage HPC
-   Choose the [Collaborative Organization](https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=17825822) of the project for which you want to create the storage volume
-   Choose the wallet with which you 'pay' for the Storage Unit
-   Choose the size. It is not possible to resize it later on, so don't choose too small, but also don't choose too large because it will cost more credits.
-   Give your storage volume a descriptive name so you can recognize it later on (e.g. use the name of the project or experiment)

## Create a workspace
A workspace can also be called a 'Virtual Machine' or a 'Server'. It is a temporary 'remote' machine that you can login to and that has you can use to perform analyses or model runs. You 'pay' for the machine with the credits from your wallet. The more compute power you select the more credits it costs and the sooner your wallet will be empty.

### How to create a workspace?
In the Research Cloud portal:

-   Click 'Create new workspace'
-   Select application (Ubuntu, R-studio etc.)
-   Choose the [Collaborative Organization](https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=17825822) of the project for which you want to create the workspace
-   Skip step 3 'Datasets'
-   Choose the wallet with which you 'pay' for the Storage Unit
-   Select Cloud provider (Surf HPC Cloud)
-   Select the size of your workspace (# of Cores and RAM, or when relevant GPU)
-   Select persistent storage volume (see above how to create one)
-   Set expiration date (default setting is 1 week). Important: on this date the machine and all data on it will be deleted without warning. Only data on the Storage volume will remain. The expiration date can be changed later on.
-   Give the workspace a descriptive title that you can recognize later on.
-   Click Submit


## Pausing, Resuming, Deleting a workspace
You always need a wallet to create a workspace, by default a workspace can only be paused, resumed and deleted by the one that has created it. You can use SRAM to give persons permission to PAUSE, RESUME and DELETE a workspace that is created by someone else. It is also possible to share a wallet with a member of your CO in SRAM. See [Add collaborators to existing project](accounts.qmd#add-collaborators-to-existing-project).


## Getting access to your workspace

There are several ways to login to your workspace. 

### SSH (secure shell protocol). 

For some workspaces this is the only option to login to your workspace. These are typically command line only workspaces (e.g. Ubuntu 20.04 command line).

Since this method also works for most other workspace types, it could also be a useful option in some other cases, e.g. when you want to [copy a file from your laptop to the workspace](manuals/ssh-data-transfer-methods.qmd).

The research cloud documentation provides instructions on [how to set up SSH for research cloud](https://servicedesk.surf.nl/wiki/display/WIKI/Log+in+to+your+workspace#Logintoyourworkspace-AccessaworkspacewithSSH).

To connect to the workspace from a Windows computer you need specific software to use a ‘shell’ (also known as ‘terminal’), examples include Git Bash, PuTTY and MobaXterm. If you need to install something new, we would recommend [MobaXterm](https://mobaxterm.mobatek.net/).

On MacOS and Linux machines you can use the standard ‘Terminal’.

### RDP and Browser access
These method can be used for workspaces that have a Graphical user interface.

#### Browser access
Jupyter and RStudio workspaces can be accessed via your web browser by clicking the yellow access button. Other workspaces that show a valid URL when you click the workspace in the research cloud dashboard, can also be accessed by clicking the yellow access button.

#### RDP (Remote Desktop Protocol)


## Getting data inside your workspace
### Mounting online storage


### Transferring data
-   Upload from your laptop (Jupyter Notebook and Rstudio Workspaces)
-   scp/ssh (most workspaces)
-   Download (Ubuntu Desktop workspaces)
-   irods  ()
-   rclone

