---
title: "Getting started"
---

## How to get on board

This page elaborates on the procedure described on Virtual Research Environments (VREs) on the [UU website](https://www.uu.nl/en/research/research-data-management/tools-services/software-and-computing/virtual-research-environments).

There are several situations that may apply to you:  

1. My project team is currently not using Research cloud and I want to start on Research cloud  
[Start here](#onboarding-procedure)  

2. Someone in my project team is already using Research cloud and I need access  
[Start here](#add-collaborators-to-existing-project)  

3. I think Research Cloud is interesting for my current project but I am not sure  
[Start here](#onboarding-procedure)  

## Onboarding procedure

This is a flowchart describing the Onboarding procedure for new projects, find descriptions of the steps below the flowchart.

```{mermaid}
flowchart TD
  A[1 Intake meeting] --> B{Onboarding}
  B -- account --> C[2 Create collaboration<br> in SRAM]
  B -- training --> D[<a href='https://www.uu.nl/en/research/research-data-management/workshops/getting-started-with-virtual-research-environments-vres'>Getting Started with VRE</a>]
  B -- budget --> F["3 Apply for credits<br>#bull; UU credits via intake<br>#bull; Small compute application<br>#bull; Project budget"]
  C --> E
  D ----> E[4 Log in on Research Cloud]
  F --> E
  E --> J[Create your first workspace!]

  style F text-align:left

```

### 1. Plan an intake with the Research Engineering team
During a 30 minute online meeting we will discuss the requirements for you research project and discuss the following topics:

* The appropriate solution. RDM Support will help you determine which solution will meet the requirements of your research. 
* The required configuration. RDM Support will discuss the software and configuration that your research needs and how we can help you make your own software or scripts available.
* Other requirements. RDM Support can consult on related needs, such as research data management, to facilitate a complete and integral solution for your research.
* Funding arrangements. The VRE costs are covered on a pay-per-use basis. If you do not have a budget available, RDM Support can help you apply for “SURFsara credits” to get you started for a limited time. We can also help you with applying for more credits via SURF and NWO.

The Research engineer who is doing the intake has experience with the systems and can quickly assess your needs when looking together at your software. The engineer will advice you about how to proceed. When Research cloud meets the technical requirements of your project, we will arrange administration that is necessary to get started directly during the intake.

[Schedule an intake meeting](https://outlook.office365.com/owa/calendar/HPCSupport1@solisservices.onmicrosoft.com/bookings/).

{{< include ./_end_date.qmd >}}

### 2. Request a collaboration in SRAM

This will be done for you by the UU support team after intake meeting (step 1). 

::: {.callout-note collapse="true"}
## What is SRAM?

SRAM (SURF Research Access Management) is a service to manage access to research resources, intended for Dutch led research collaborations. [More information](https://servicedesk.surf.nl/wiki/display/IAM/SURF+Research+Access+Management).
:::

::: {.callout-note collapse="true"}
## What is a collaboration?

A Collaboration (also known as Collaborative Organisation, or CO) is an ad-hoc group of people who are allowed to work together by sharing resources. As a scientist you can easily make a CO. That way, you can invite other researchers to join your efforts in Research Cloud, and you can then self-organise yourselves to distribute tasks, including administering the CO. [More information](https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=17825822).

:::

### 3. Request funding
There are several ways to request funding for credits:  

**UU Budget**
This is typically granted during an intake meeting (see step 1 above).

**Small Compute application**
Via a Small Compute application (SURF) 50.000 CPU hours and/or 5.000 GPU hours can be requested for your project for 1 calendar year. A Small Compute application can be done one time per calendar year. The application procedure is relatively simple and fast. [More information](funding.qmd). Most users first use the UU budget before they submit a Small compute application. 

**Large Compute application**
A Large Compute application can done if you require more resources than provided via the Small compute application. [More information](funding.qmd).

**Project budget**
It is possible to pay for credits via your own project budget. Discuss the possiblities during an intake meeting (see step 1 above).

### 4. Log in to Research cloud 

After your collaboration and your budget (aka wallet) have been created you can start working with Research Cloud!

The url of the Research cloud portal is: `surfresearchcloud.nl`, or click the link below to go to the portal.

[Research Cloud portal](https://portal.live.surfresearchcloud.nl/)

## Add collaborators to existing project

When you want to onboard new project member in Research cloud you should think about the rights you want to grant them:

::: {.callout-note collapse="true"}
## Should the new project member only have access to running workspaces? 

Perform step 1 below
:::

::: {.callout-note collapse="true"}
## Should the new project member be able to pause, resume and delete workspaces that I create? 

Perform step 1 and 2 below
:::

::: {.callout-note collapse="true"}
## Should the new project member be able to create new workspaces using the project budget? 

Perform step 1, 2(optional), and 3
:::

::: {.callout-tip}
## Security Best Practice

Only grant collaborators the permissions they need. Set an expiration date for memberships when inviting people to your collaboration. See our [tips for secure collaboration](responsible-use.qmd#collaboration-and-access-management) for more guidance.
:::

### 1. Invite a new collaborator
SURF Research Cloud uses SRAM to control who can access your project's workspaces and resources. 

Before someone can use workspaces in your collaboration, they must first be invited and accept the membership. Once they accept, they can log in to running workspaces but by default they cannot create, pause, or delete workspaces until you grant additional permissions. Inviting collaborators through SRAM ensures secure, traceable access management and lets you control exactly what each team member can do.

See this guide to [invite collaborators to your collaboration (project).](https://servicedesk.surf.nl/wiki/display/IAM/Invite+admins+and+members+to+a+collaboration)

::: {.callout-note collapse="true"}
## Who can I invite?

It is possible to invite anyone who has an email address to join your project. Students and employees from most Universities (and Universities of Applied Sciences) will be able to login to SRAM using their institution credentials. Collaborators from abroad or e.g. private sector can create an [eduID](https://eduid.nl/) first and then use that to login to SRAM and accept the invitation.
:::

### 2. Grant Workspace Admins Rights
By default, only the person who creates a workspace can pause, resume, or delete it. This can be limiting when working in teams.

SRAM groups solve this by allowing you to share workspace management rights with other team members. By adding collaborators to the `src_ws_admin` group, you give them control over the workspaces in your collaboration without giving them access to the project budget. This is useful when multiple team members need to manage workspaces but shouldn't be able to create new resources or spend credits.

Follow the guides on how to [create and manage groups](https://servicedesk.surf.nl/wiki/display/IAM/Manage+groups+of+collaboration+members) and how to grant members of your collaboration the right to [pause, resume and delete workspaces](https://servicedesk.surf.nl/wiki/display/WIKI/Sharing+control%3A+workspace+admin)

### 3. Grant Wallet Access
By default, only collaboration admins can create new workspaces. This can slow down research when team members need to provision their own resources.

SRAM groups enable you to delegate workspace creation rights. By adding collaborators to the `src_co_wallet` group, you give them permission to create workspaces and storage volumes using the project's shared budget.

This is beneficial for collaborative research where multiple team members need autonomy to start their own workspaces, but should only be granted to trusted members since they'll be able to spend project credits.

Follow the guides on how to [create and manage groups](https://servicedesk.surf.nl/wiki/display/IAM/Manage+groups+of+collaboration+members) and how to grant members of your collaboration the right to [create new workspaces using the wallet of your project](https://servicedesk.surf.nl/wiki/display/WIKI/Access+to+project+wallet)

## Next
When your collaboration and wallet is ready, see this page for [first steps](first-steps.qmd).
