---
title: "What is Research Cloud"
---

## Introduction

SURF ResearchCloud (SRC) is a service that allows you to use the vast computational power offered 
by datacenters with almost the same ease-of-use as using your own laptop. 
The complex infrastructure behind the scenes is presented to you as a *workspace*. Think
of a workspace as a laptop-in-the-cloud that you access using your web browser or another
application (for instance, the Remote Desktop application or a command line shell).
Your web browser displays the screen content of this workspace and allows you to interact with
it using your keyboard and mouse. 

Workspaces are preconfigured with one or more applications, ranging from RStudio, Jupyter Notebooks, Matlab, to plain Windows or Linux virtual machines where the user installs their own software. Workspaces are also scalable:
computational power, GPU drivers and extra storage can be ordered with a single mouse click.
You can select a workspace type that suites your needs from a catalog in 
the [SRC web portal](https://portal.live.surfresearchcloud.nl). 
Workspaces are preconfigured for the user by support staff and can be extended on request to suit a variety of research domains and analysis methods. 
Should analysis applications for your domain not yet be covered, the support staff is happy to assist 
and to make additions to the catalog. Simply [contact us](contact.qmd) if you have questions about or requests for the catalog.

Creating a workspace is easily achieved in the ResearchCloud web portal with a few clicks. The 
datacenter service will set aside some compute power for you. 
The datacenter subsequently creates a workspace and prepares it for you with applications preinstalled. 
This whole process takes approximately 10 to 30 minutes, depending on the type of workspace.

A workspace is offered on-demand and on a pay-as-you-go basis. 
It saves you much hassle: no need to buy and maintain computer hardware and
your favorite applications come conveniently preinstalled for you.
This resource leasing concept is a cost effective solution if you plan to use it part-time, 
or if you seek to avoid to invest in expensive computer hardware, software or related IT-skills.
Once you are done with using your workspace, just delete it in the SRC web portal.

**Example workspaces**

See [here](workspace-catalogue.qmd)) for a selection of available workspace types.


**Resources available for a single workspace**  

When creating workspaces to run on the SURF datacenter, the following computational resources are available:

* up to 80 CPU cores  
* up to 480 GB RAM  
* up to 4 GPU drives (NVIDIA A10)  
* up to 2 TB storage

However, is also possible to use the ResearchCloud portal to create workspaces running on commercial datacenters (e.g. Microsoft Azure), in which case more resources may be available.
This may be suitable for some use cases, although it comes with significantly higher costs and may not be desirable from a data privacy perspective.

[Contact us](contact.qmd) if you are unsure about the computational needs for your project and whether ResearchCloud is a good fit.

## Designed with consortia and other Collaborative use in mind
SURF Research Cloud uses the concept of a 'collaboration' to facilitate working together in project teams.
A collaboration may be viewed as a *virtual* organization, with members that can originate
from different research institutes, or from the private sector. A collaboration can accommodate a virtual organization the size of a European research project consortium. In contrast, it might also consist of a single member, e.g. a researcher in need of compute power or a private workspace.

Managing memberships of the collaboration is done via a self-service portal (called [SRAM](https://servicedesk.surf.nl/wiki/display/WIKI/SURF+Research+Access+Management), 
short for SURF Research Access Management. For example, a researcher can give (temporary) access to PhDs or students.

It is important to understand that SRC assumes all members of the collaboration to be 
contractually or otherwise bound to work together.  
Hence the costs related to a workspace ordered by a single member of the collaboration are 
effectively charged to the collaboration. In addition, the workspace is automatically accessible
to all members of the collaboration.

## Funding
There are several ways to request computing time for SRC. The easiest and fastest way (and recommended first step)
is to [contact UU Research IT](onboarding.qmd#plan-an-intake-with-the-research-engineering-team).
A short intake meeting will get you started. Additionally, more computing time can be [requested via Surf or NWO](funding.qmd).

## Getting started
[Plan an intake meeting](onboarding.qmd#plan-an-intake-with-the-research-engineering-team) to get started. After a 30 minute intake you will have everything ready to start your first workspace. More info about the onboarding procedure can be found [here](onboarding.qmd)

Practical instructions to get started on SRC can be found [here](first-steps.qmd).