
---
title: "Terms of Use"
---

# Responsible Use

Find below the Terms of Use for Research Cloud Workspaces owned and maintained by the [Utrecht University VRE team](https://www.uu.nl/en/research/research-data-management/tools-services/software-and-computing/virtual-research-environments).

[Practical tips for UU employees for responsible and secure use of Surf Research cloud](responsible-use.qmd).

# Terms of Use

The following terms and conditions govern all use of workspaces, subsequently referred to as UU Workspaces, that are deployed and managed via the SURF ResearchCloud service, and owned by a collaboration that is coordinated by Utrecht University, as well as all content, services and products available at or through these workspaces. UU Workspaces are operated by or on behalf of Utrecht University. UU Workspaces is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on www.uu.nl by Utrecht University (collectively, the “Agreement”).Please read this Agreement carefully before accessing or using UU Workspaces. By accessing or using any part of UU Workspaces, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access UU Workspaces or use any of its services. If these terms and conditions are considered an offer by Utrecht University, acceptance is expressly limited to these terms. 

## 1. Your UU Workspaces Account 

If you have a UU Workspaces account then you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account. You must immediately notify UU Workspaces business administration via UU Workspaces@uu.nl of any unauthorized uses of your account or any other breaches of security. Utrecht University will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. 

## 2. Responsibility of Contributors 

If you submit material (“Data”) to UU Workspaces, you are entirely responsible for the content of, and any harm resulting from, that Content. By submitting, you represent and warrant that: * the use of the Data will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party; 

if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content; 

you have fully complied with any third-party licenses relating to the Data, and have done all things necessary to successfully pass through to end users any required terms; 

the Data does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content; 

the Data is not spam, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing); 

## 3. User Data License 

Utrecht University has the right (though not the obligation) to, in Utrecht University’s sole discretion (i) refuse or remove any content that, in Utrecht University’s reasonable opinion, violates any Utrecht University policy or is in any way harmful or objectionable, in Utrecht University’s sole discretion. Utrecht University will have no obligation to provide a refund of any amounts previously paid. 

## 4. Responsibility of UU Workspaces Visitors 

You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The UU Workspaces and related services may contain technical inaccuracies, typographical mistakes, and other errors. Utrecht University disclaims any responsibility for any harm resulting from the use by visitors of the UU Workspaces and related services, or from any downloading by those visitors of content there posted. 

## 5. Content Posted on Other Websites 

We have not reviewed, and cannot review, all of the material, including computer software, made available through any UU Workspaces websites and webpages to which UU Workspaces Website and related services links, and that link to UU Workspaces. Utrecht University does not have any control over those non-UU Workspaces websites and webpages, and is not responsible for their contents or their use. By linking to a non-UU Workspaces website or webpage, Utrecht University does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Utrecht University disclaims any responsibility for any harm resulting from your use of non-UU Workspaces websites and webpages. 

## 6. Copyright Infringement and DMCA Policy 

As Utrecht University asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by UU Workspaces violates your copyright, you are encouraged to notify Utrecht University. Utrecht University will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. Utrecht University will terminate a visitor’s access to and use of the Website if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of Utrecht University or others. In the case of such termination, Utrecht University will have no obligation to provide a refund of any amounts previously paid to Utrecht University. 

## 7. Intellectual Property 

This Agreement does not transfer from Utrecht University to you any Utrecht University or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with Utrecht University. Utrecht University, the UU Workspaces website and related services, the Utrecht University logo, and all other trademarks, service marks, graphics and logos used in connection with UU Workspaces are trademarks or registered trademarks of Utrecht University or Utrecht University’s licensors. Other trademarks, service marks, graphics and logos used in connection with UU Workspaces may be the trademarks of other third parties. Your use of UU Workspaces grants you no right or license to reproduce or otherwise use any Utrecht University or third-party trademarks. 

## 8. Attribution 

Utrecht University reserves the right to display attribution links such as ‘Powered by UU Workspaces,’ theme author, and font attribution in your content footer or toolbar. Footer credits and other such expressions may not be removed regardless of upgrades purchased. 

## 9. Changes 

Utrecht University reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to UU Workspaces following the posting of any changes to this Agreement constitutes acceptance of those changes. Utrecht University may also, in the future, offer new services and/or features through UU Workspaces website or related services (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement. 

## 10. Termination 

Utrecht University may terminate your access to all or any part of UU Workspaces at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your UU Workspaces account (if you have one), you may simply discontinue using UU Workspaces and/or cancel your registration and delete the stored information. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. 

## 11. Disclaimer of Warranties 

UU Workspaces are provided “as is”. Utrecht University and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Utrecht University nor its suppliers and licensors, makes any warranty that the UU Workspaces website and related services will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, UU Workspaces at your own discretion and risk. 

## 12. Limitation of Liability 

In no event will Utrecht University, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Utrecht University under this agreement during the twelve (12) month period prior to the cause of action; (v) The services offered via UU Workspaces are for research purposes only, and are not to be used to guide clinical decisions. We make no representation that these results are accurate. Utrecht University shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law. 

## 13. General Representation and Warranty 

You represent and warrant that (i) your use of UU Workspaces will be in strict accordance with Utrecht University Information Security policies and privacy policies, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the country in which UU Workspaces resides or the country in which you reside) and (ii) your use of UU Workspaces will not infringe or misappropriate the intellectual property rights of any third party. 

## 14. Indemnification 

You agree to indemnify and hold harmless Utrecht University, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of UU Workspaces, including but not limited to your violation of this Agreement. 

## 15. Miscellaneous 

This Agreement constitutes the entire agreement between Utrecht University and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Utrecht University, or by the posting by Utrecht University of a revised version. Except to the extent applicable law, if any, provided otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the Netherlands. 

This document was adapted from [nestor.science.uu.nl](nestor.science.uu.nl)  and is licensed as [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). 

Last update: May 2, 2023
